crm/urls.py
from django.conf.urls import include, url
from crm import views, purchase_history, activity, campaign

app_name = "crm"

purchase_history_patterns = ([



    url(r'^student/(?P<pk>[^/]+)/purchase_history/$', purchase_history.purchases, name="purchases"),

], 'purchase_history')

activity_patterns = ([



    url(r'^student/(?P<pk>[^/]+)/activities/$', activity.list, name="list"),

], 'activity')

campaign_patterns = ([

    url(r'^create/$', campaign.campaign_create, name="campaign_create"),
    url(r'^list/$', campaign.campaign_list, name="campaign_list"),
    url(r'^(?P<pk>[^/]+)/detail/$', campaign.campaign_detail, name="campaign_detail"),
    url(r'^(?P<pk>[^/]+)/edit/$', campaign.campaign_edit, name="campaign_edit"),
    # url(r'^(?P<pk>[^/]+)/add_new_vendor/$', campaign.add_vendor, name="add_vendor"),
    # url(r'^(?P<pk>[^/]+)/add_vendor/$', campaign.existing_vendors, name="existing_vendors"),
    # url(r'^(?P<pk>[^/]+)/list_vendors/$', campaign.vendors, name="vendors"),
    # url(r'^vendor/(?P<pk>[^/]+)/remove/$', campaign.remove_vendor, name="remove_vendor"),
    url(r'^(?P<pk>[^/]+)/add_products/$', campaign.add_products, name="add_products"),
    url(r'^(?P<pk>[^/]+)/list_products/$', campaign.products, name="products"),
    url(r'^product/(?P<pk>[^/]+)/remove/$', campaign.remove_product, name="remove_product"),
    url(r'^TargetAudience/(?P<pk>[^/]+)/create/$', campaign.target_audience_create, name="target_audience_create"),
    url(r'^(?P<pk>[^/]+)/add_new_student/$', campaign.add_customer, name="add_customer"),
    url(r'^(?P<pk>[^/]+)/add_student/$', campaign.existing_customers, name="existing_customers"),
    url(r'^(?P<pk>[^/]+)/list_student/$', campaign.customers, name="customers"),
    url(r'^student/(?P<pk>[^/]+)/remove/$', campaign.remove_customer, name="remove_customer"),

], 'campaign')


urlpatterns = [

    url(r'^', include(purchase_history_patterns)),
    url(r'^', include(activity_patterns)),
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    # url(r'^students/$', views.customers, name="customers"),
    url(r'^campaign/', include(campaign_patterns)),
    # url(r'^crm/customers/$', views.customers, name="customers"),
    url(r'^crm/contact/(?P<custm_pk>[^/]+)/paymentDetails/$', views.full_payment_details, name='full_payment_details'),


]

easyLink/urls.py
from django.conf import settings
from django.conf.urls import include, url
"""easyLink URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from sitetree.sitetreeapp import compose_dynamic_tree, register_dynamic_trees
from django.conf.urls.static import static
from erp_admin import views as erpAdminViews

urlpatterns = [
    url(r'^$', erpAdminViews.dashboard),
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('employee.urls', namespace="employee")),
    # url(r'^', include('customer.urls', namespace="customer")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('product.urls', namespace="product")),
    url(r'^crm/', include('crm.urls', namespace="crm")),
    url(r'^', include('enquiry.urls', namespace="enquiry")),
    url(r'^erp_core/', include('erp_core.urls', namespace="erp_core")),
    url(r'^', include('student.urls', namespace="student")),
    url(r'^', include('location.urls', namespace="location")),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
register_dynamic_trees(

    compose_dynamic_tree('erp_admin'),

    # or gather all the trees from `books` and attach them to `main` tree root,
    # compose_dynamic_tree('project'),
    # compose_dynamic_tree('company'),

    # compose_dynamic_tree('gst'),
    compose_dynamic_tree('employee'),
    # compose_dynamic_tree('product'),
    # compose_dynamic_tree('vendor'),
    compose_dynamic_tree('product'),

    # compose_dynamic_tree('inventory'),
    # compose_dynamic_tree('customer'),
    compose_dynamic_tree('enquiry'),
    compose_dynamic_tree('crm'),
    compose_dynamic_tree('student'),


)

enquiry/urls.py
from django.conf.urls import url, include
from enquiry import api, views, mobile_api, enquiry
from rest_framework import routers

# router = routers.DefaultRouter()
# router.register(r'enquiries', api.EnquiryViewSet, base_name="enquiry")

# m_router = routers.DefaultRouter()
# activity_router = routers.DefaultRouter()
# m_router.register(r'enquiries', mobile_api.EnquiryViewSet, base_name="enquiry")
# activity_router.register(r'activities', activity_api.ActivityViewSet, base_name="activities")

# enquiry_list = api.EnquiryViewSet.as_view({'get': 'list'})
# enquiry_create = api.EnquiryViewSet.as_view({'get': 'create_form'})
# enquiry_retrieve = api.EnquiryViewSet.as_view({'get': 'retrieve'})

# activity_list = activity_api.ActivityViewSet.as_view({'get': 'list'})
# activity_detail = activity_api.ActivityViewSet.as_view({'get': 'retrieve'})
# quotation_list = quote.QuotationViewSet.as_view({'get': 'list'})

app_name = "enquiry"

urlpatterns = [
    # url(r'^enquiries/', enquiry_api.enquiry_list, name="enquiry_list"),
    url(r'^enquiries/$', enquiry.list, name="list"),
    url(r'^enquiries/create/$', enquiry.create, name="create"),
    url(r'^enquiries/code_settings/$', views.code_settings, name='code_settings'),
    # url(r'^enquiries/(?P<pk>[^/]+)/$', enquiry_retrieve, name="detail"),
    url(r'^enquiries/(?P<pk>[^/]+)/delete/$', enquiry.delete, name="delete"),
    url(r'^enquiry/(?P<pk>[^/]+)/details/$', enquiry.enquiry_detail, name="enquiry_detail"),
    url(r'^enquiry/(?P<pk>[^/]+)/edit/$', enquiry.edit, name="edit"),
    url(r'^enquiry/activity/(?P<pk>[^/]+)/complete/$', enquiry.complete_activity, name="complete_activity"),
    url(r'^enquiry/(?P<pk>[^/]+)/edit_status/$', enquiry.edit_status, name="edit_status"),
    url(r'^enquiry/(?P<pk>[^/]+)/remark/$', enquiry.add_remark, name="add_remark"),
    url(r'^enquiry/(?P<pk>[^/]+)/onhold/$', enquiry.add_onhold_remark, name="add_onhold_remark"),


    # /enquiries/code_settings/
    # Activity urls
    url(r'^enquiries/(?P<enquiry_pk>[^/]+)/activities/create/$', views.create_activity, name="add_activity"),
    url(r'^activitie/(?P<pk>[^/]+)/edit/$', views.edit_activity, name="edit_activity"),
    url(r'^activitie/(?P<pk>[^/]+)/delete/$', views.delete_activity, name="delete_activity"),
    url(r'^activitie/(?P<pk>[^/]+)/view/$', views.view_activity, name="view_activity"),
    # url(r'^quotations/$', quotation_list, name="quotations"),
    # url(r'^api/', include(router.urls, namespace='api')),
    # url(r'^m/api/', include(m_router.urls, namespace='m-api')),
    # url(r'^api/', include(activity_router.urls, namespace='m-api')),
    # url(r'^quote/', include(router.urls, namespace='quote')),
    url(r'^reports/office/$', enquiry.filter_based_on_office, name="filter_based_on_office"),
    url(r'^reports/streamwise/$', enquiry.stream_wise_report, name="stream_wise_report"),
    url(r'^enquiries/(?P<pk>[^/]+)/activity_type/$', views.create_activity_type, name="create_activity_type"),


]
# GET /m/api/enquiries/ => enquiry list
# GET /m/api/enquiries/choices => enquiry choice fields
# POST /m/api/enquiries/  => create enquiry
# PUT /m/api/enquiries/{pk}  => update enquiry
# DELETE /m/api/enquiries/{pk}  => delete enquiry

product/urls.py
from django.conf.urls import include, url
from product import api, views

app_name = "product"

# api_patterns = ([

#     # url(r'^invoices/$', api.invoices, name="invoices"),
#     url(r'^products/$', api.ProductList.as_view()),

#     # url(r'^invoice/(?P<code>[^/]+)/payments/$', api.payment_details, name="payment_details"),

# ], 'api')


urlpatterns = [
    # url(r'^api/', include([
    #     # router.urls,
    #     url(r'^products/', include([
    #         url(r'^select_list/$', api.product_select_options, name="select_list"),
    #     ])),
    #     # get active products -api
    #     # url(r'^products/$', api.all_products, name="all_products"),

    # ], namespace='api')),
    url(r'^programs/add_program/$', views.add_products, name='add_products'),
    url(r'^programs/listProgram/$', views.view_products, name='view_products'),
    url(r'^programs/(?P<pk>[^/]+)/detail/$', views.detail, name='detail'),
    url(r'^programs/edit_program/(?P<product_pk>[^/]+)/$',
        views.edit_product, name='edit_product'),
    url(r'^programs/code/settings/$', views.code_settings, name='code_settings'),
    url(r'^programs/(?P<pk>[^/]+)/delete/$', views.delete, name='delete'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # url(r'^import/$', views.import_data, name="import"),


]

crm/models.py
from django.db import models

from erp_core.models import ErpAbstractBaseModel
from django.core.validators import MinValueValidator
from location.models import City
# from customer.models import Contact, Customer
# from project.models import Project
# Create your models here.


class Media(ErpAbstractBaseModel):

    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)


class CampaignCategory(ErpAbstractBaseModel):

    name = models.CharField(max_length=100)
    # eg: print,ad

    def __str__(self):
        return str(self.name)


class Campaign(ErpAbstractBaseModel):
    ONLINE = 'online'
    OFFLINE = 'offline'
    TYPES = (
            (ONLINE, "online"),
            (OFFLINE, "offline"),
    )
    name = models.CharField(max_length=255)
    media_type = models.CharField(max_length=30, choices=TYPES, default=TYPES[0])
    budget = models.DecimalField(max_digits=20, decimal_places=2, default=0, validators=[MinValueValidator(0)])
    description = models.TextField()
    offer_details = models.TextField(null=True, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    no_of_responses = models.PositiveIntegerField(null=True, blank=True, default=0)
    no_of_conversions = models.PositiveIntegerField(null=True, blank=True, default=0)
    group = models.TextField('Campaign Group', null=True, blank=True)  # onam

    media = models.ForeignKey(Media, on_delete=models.CASCADE)
    category = models.ForeignKey(CampaignCategory, on_delete=models.CASCADE)
    location = models.ForeignKey(City, on_delete=models.CASCADE)
    # project = models.OneToOneField(Project, null=True, blank=True)

    def __str__(self):
        return str(self.name)


class CampaignVendor(ErpAbstractBaseModel):
    publisher = models.BooleanField(default=False)

    campaign = models.ForeignKey(Campaign, related_name="%(class)ss", on_delete=models.CASCADE)

    # class Meta:
    #     unique_together = (("campaign", "vendor"),)

    def __str__(self):
        return str(self.campaign)


# class CampaignProduct(ErpAbstractBaseModel):
#     campaign = models.ForeignKey(Campaign, related_name="%(class)ss", on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)

#     class Meta:
#         unique_together = (("campaign", "product"),)

#     def __str__(self):
#         return str(self.campaign)


class TargetAudienceCampaign(ErpAbstractBaseModel):
    SEX = (
        ('Female', 'Female'),
        ('Male', 'Male'),
        ('Others', 'Others'),
    )
    gender = models.CharField(max_length=8, choices=SEX)
    age_limit = models.CharField(max_length=8)
    income_range = models.PositiveIntegerField()

    campaign = models.OneToOneField(Campaign, related_name="audience", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.campaign)


# class CampaignCustomer(ErpAbstractBaseModel):
#     campaign = models.ForeignKey(Campaign, related_name="campaign_customers", on_delete=models.CASCADE)
#     customer = models.ForeignKey(Customer, related_name="campaign_sets", on_delete=models.CASCADE)

#     def __str__(self):
#         return str(self.campaign)

#     class Meta:
#         unique_together = (("campaign", "customer"),)

crm/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class CampaignForm(ModelForm):

    class Meta:
        model = Campaign
        widgets = {
            "name": forms.TextInput(attrs={'class': "form-control", 'required': "required"}),
            "media_type": forms.Select(attrs={'class': "form-control"}),
            "budget": forms.NumberInput(attrs={'class': "form-control"}),
            "description": forms.Textarea(attrs={'class': "form-control", 'rows': 3}),
            "offer_details": forms.Textarea(attrs={'class': "form-control", 'rows': 3}),
            "start_date": forms.DateInput(attrs={'class': "form-control tdate", 'id': "start_date"}),
            "end_date": forms.DateInput(attrs={'class': "form-control tdate", 'id': "end_date"}),
            # "no_of_responses": forms.NumberInput(attrs={'class': "form-control"}),
            # "no_of_conversions": forms.NumberInput(attrs={'class': "form-control"}),
            # "group": forms.TextInput(attrs={'class': "form-control"}),
            "media": forms.Select(attrs={'class': "form-control"}),
            "category": forms.Select(attrs={'class': "form-control"}),
            "location": forms.Select(attrs={'class': "form-control"}),

        }
        fields = ['name', 'media_type', 'budget', 'description', 'offer_details', 'start_date', 'end_date','media', 'category', 'location']


class CampaignVendorForm(ModelForm):

    class Meta:
        model = CampaignVendor
        widgets = {
            "publisher": forms.CheckboxInput(attrs={}),
        }
        fields = ['campaign', ]


class CampaignPublisherForm(ModelForm):

    class Meta:
        model = CampaignVendor
        widgets = {
            "publisher": forms.CheckboxInput(attrs={}),


        }
        fields = ['publisher', ]


# class CampaignProductForm(ModelForm):

#     class Meta:
#         model = CampaignProduct
#         widgets = {
#             "product": forms.Select(attrs={'class': "form-control"}),


#         }
#         fields = ['product', ]


class TargetAudienceCampaignForm(ModelForm):

    class Meta:
        model = TargetAudienceCampaign
        widgets = {
            "gender": forms.Select(attrs={'class': "form-control"}),
            "income_range": forms.NumberInput(attrs={'class': "form-control"}),
            "age_limit": forms.TextInput(attrs={'class': "form-control"}),
        }
        fields = ['gender', 'income_range', 'age_limit']


# class CampaignCustomerForm(ModelForm):

#     class Meta:
#         model = CampaignCustomer
#         widgets = {
#             "customer": forms.Select(attrs={'class': "form-control", 'required': "required"}),


#         }
#         exclude = ['campaign', ]

crm/views.py
# from invoice.models import InvoicePaymentTerms
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib import messages
# from invoice.models import Invoice
# from customer.models import Customer, Contact
from erp_core.pagination import paginate
# from crm.filters import CustomerFilter
import datetime
from student.models import Student


def dashboard(request):
    return render(request, "crm/dashboard.html")


# def customers(request):

#     f = CustomerFilter(request.GET)
#     contacts = Contact.objects.all()
#     contacts, pagination = paginate(request, queryset=f.qs, per_page=20, default=True)

#     # print(f.form)
#     context = {
#         'contacts': contacts,
#         # 'status': Customer.STATUSES,
#         'pagination': pagination,
#         'filter': f,
#     }

#     return render(request, "crm/customers.html", context)


def full_payment_details(request, custm_pk):
    # contact = get_object_or_404(Contact, id=custm_pk)

    date_check = request.GET.get('month_year')
    if date_check:
        date_for_check = datetime.datetime.strptime(date_check, "%B %Y").date()
    else:

        date_for_check = datetime.date.today()

    payments = InvoicePaymentTerms.objects.filter(
        invoice__contact__pk=custm_pk,
        date__month=date_for_check.month,
        date__year=date_for_check.year
    )
    payments, pagination = paginate(request, queryset=payments, per_page=20, default=True)

    # payments = InvoicePaymentTerms.objects.filter(invoice__contact=contact)

    context = {
        # 'contact': contact,
        'payments': payments,
        'custm_pk': custm_pk,
        'pagination': pagination,
    }

    return render(request, "crm/full_payment_details.html", context)

crm/templates/crm/campaign/campaign_wise_report.html
{% extends "erp_admin/base.html" %}
{% load static tz util %} {% get_current_timezone as TIME_ZONE %}
{% block title %} Daily Report{% endblock title %}
{% block head %}
<style type="text/css">

.white{
color: #fff!important;
text-align: center!important;
}

.rw-style{
margin-right: 0px;
margin-left: 0px;
padding:15px;
}
.table>thead>tr>th{
    color: #2E86C1!important;
    font-size: 15px!important;
    
}
.head-syle{
    font-size:20px;
    color:#000;

}
@media print {

  a[href]:after {
    content: none!important;
  }
  .noprint{
    display:none!important;

  }
  }
</style>
{% endblock head %}
{% block content %}
<div class="block">
    <div class="row">
        <div class="col-sm-6 col-xs-6 col-lg-6 col-sm-6" style="padding-left:30px;">
            <a href="{% url 'report:dashboard' %}">Back</a>
        </div>

        <div class="col-md-6 col-sm-6 col-xs-6 col-lg-6">

             <a onclick="printDiv()" class="btn btn-primary btn-sm pull-right" target="_blank"> <i class="fa fa-print fa-fw"></i> Print</a>
             <a href="{% url 'report:campaign' %}" class="btn btn-primary btn-sm pull-right"> <i class="fa fa-bars"> </i> Campigns List</i></a>
        </div>
    </div>
    <div class="row show-grid">
        
            <div class="col-sm-6 col-xs-12">
                <h3>Enquires Based on Campaign</h3>
            </div>
        
    </div>
    
    <div class="row show-grid" style="padding-right:15px;">
        <form id="form" action="{% url 'report:campaign_wise_report' %}" method="post">
            {% csrf_token %}
            <div class="col-sm-3">
                <div class="form-inline">
                    <div class="form-group">
                        <select class="form-control" name="campaign" id ="campaign" required="required">
                            <option value=""> --FILTER BY CAMPAIGN-- </option>
                            {% for campaign in campaigns %}
                                <option value="{{ campaign.id }}" {% compare_uuid current_campaign campaign.id %}>{{ campaign }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-sm-2">
                <label>Select Month & Year </label>
            </div>
            <div class="col-sm-3">
                <input type="text" name="month_year" class="form-control tdate" value="{{date_for_check}}">
            </div>
            <div class="col-sm-2">
                <button type="submit" name="search" class="btn btn-primary"><i class="fa fa-search"></i> Search</button>
            </div>
            <div class="col-sm-2">
                <a href="{% url 'report:campaign_wise_report' %}"class="btn btn-primary"><i class="fa fa-refresh"></i> Refresh</a>
            </div>
            
        </form>
    </div>
    <div class="row">
        <div class="col-sm-12 pull-right">
        </div>
    </div>
</div>

<div class="block">
    <div class="row show-grid">
        <div class="col-sm-12">
        <div id="print_data">
            <div class="table-responsive">
           {% if campaign_ob %}
           <div class="col-sm-6 head-syle">
             Campaign : {{campaign_ob}}
            </div>
            <div class="col-sm-6 head-syle" align="right"> 
             Date :  {{date_for_check|date:'M/Y'}}
            </div>
            {% endif %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Leads (Contact)</th>
                        <th>Status</th>
                        <th>Priority</th>
                    </tr>
                </thead>
                <tbody>
                    {% for enquiry in enquires %}
                        <tr class="">
                            <td scope="row">{{ forloop.counter }}</td>
                            <td>
                                <a href="{% url 'enquiry:enquiry_detail' enquiry.pk %}">{{ enquiry.customer.user.first_name }} {{ enquiry.customer.user.last_name }}</a>
                            </td>
                            <td>
                                {% if enquiry.status.value == "REJECTED" %}
                                    <span class="label status status-open">Entry</span>
                                {% else %}
                                    <span class="label status status-open">{{ enquiry.status|title }}</span>
                                {% endif %}
                            </td>
                            <td>
                                {{ enquiry.priority|title}}
                            </td>
                           
                            
                        </tr>
                        {% empty %}
                        <tr><td colspan="8">No Leads </td></tr>
                    {% endfor %}
                    {% if count %}
                    <tr>
                        <td colspan="8" style="color:#065E9A; font-size:20px;"> Total : {{ count }}</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
            </div>

        </div>
        <div>
        <div id="pagination" align="center">
            {{pagination|safe}}
        </div>
    </div>
</div>


{% endblock content %}
{% block scripts %}
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>

<script>
$(document).ready(function(){
        

    $('.tdate').daterangepicker({
      "singleDatePicker": true,
       "autoUpdateInput":false,
       "autoApply": true,
       "showDropdowns": true,
      locale: {
        format: 'MMMM YYYY',
      },

    }, function(start, end, label) {
      //console.log(start.toISOString(), end.toISOString(), label);
    });



    $('.tdate').on('apply.daterangepicker', function(ev, picker) {
        $(this).val(picker.startDate.format('MMMM YYYY'));
    });

    $('.tdate').on('cancel.daterangepicker', function(ev, picker) {
        $(this).val('');
    });

    $("#campaign").select2({
    maximumSelectionLength: 10,
    allowClear: true,
    placeholder: "SELECT CAMPAIGN",

    });
});

</script> 
<script type="text/javascript">
    function printDiv() {    
    var printContents = document.getElementById('print_data').innerHTML;
    

    var originalContents = document.body.innerHTML;

     document.body.innerHTML = printContents;
    
     window.print();
     document.body.innerHTML = originalContents;
    }
</script>  

{% endblock scripts %}

crm/templates/crm/campaign/customers.html
{% extends "erp_admin/base.html" %}{% load humanize %}
{% load static %}
{% block head %}
<style>
.table>thead>tr>th{
    color: #00ABE7!important;
    font-size: 15px!important;
    
}

.fabutton {
  background: none;
  padding: 0px;
  border: none;
}
.padco{
padding-bottom:10%;
}
</style>

{% endblock head %}
{% block content %}


<div class="content-main">
        <div class="block padco">
            <div class="row show-grid">
                <div class="col-sm-6 col-xs-12 col-md-6 col-lg-6">
                    <h3>Students<a href=""> 
                        <!--<i class="fa fa-plus-square-o"></i>
                        -->
                        </a>
                        </h3>
                    
                </div>
                <div class="col-sm-6 col-xs-12 col-md-6 col-lg-6" align="right">
                    <h5><a href="{% url 'crm:campaign:campaign_detail' campaign.pk %}"><i class="fa fa-arrow-left">Back</i></a></h5>
                    
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-xs-12 col-md-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Remove</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for student in students %}
                            <tr>
                                <td scope="row">{{ forloop.counter }}</td>
                                
                                <td>
                                    <a href="{% url 'student:detail' student.pk %}">
                                    {{student}} 
                                    </a>
                                </td>
                                <td>

                                    <form class="delete" method="post" action="{% url 'crm:campaign:remove_customer' student.pk %}" onsubmit="remove(this, event)">{%csrf_token %}

                                            <button type="submit" class="fabutton">
                                            <i class="fa fa-trash"></i>
                                             </button>
                                    </form>
                                   
                                </td>
                                
                            
                            </tr>
                            {% empty %}
                            <tr>

                            <td colspan="3">No students added yet</td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>

                    <div id="pagination" align="right">
                        {{pagination|safe}}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block jsscript %}

<script>

$(document).ready(function(){
        
    $('form.delete').submit( function (e){
        e.preventDefault()
        e.stopPropagation()
        if(confirm('Confirm Delete')){
            this.submit()
        }
    })


});

</script>

{% endblock jsscript %}

crm/templates/crm/campaign/products.html
{% extends "erp_admin/base.html" %}{% load humanize %}
{% load static %}
{% block head %}
<style>
.table>thead>tr>th{
    color: #00ABE7!important;
    font-size: 15px!important;
    
}

.fabutton {
  background: none;
  padding: 0px;
  border: none;
}
.padco{
padding-bottom:10%;
}
</style>

{% endblock head %}
{% block content %}


<div class="content-main">
        <div class="block padco">
            <div class="row show-grid">
                <div class="col-sm-6 col-xs-12 col-md-6 col-lg-6">
                    <h3>Programs/Courses
                    <a href="{% url 'crm:campaign:add_products' campaign.pk %}"> <i class="fa fa-plus-square-o"></i></a>
                    </h3>
                    
                </div>
                <div class="col-sm-6 col-xs-12 col-md-6 col-lg-6" align="right">
                    <a href="{{ request.META.HTTP_REFERER }}">Back</a>
                    
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-xs-12 col-md-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Remove</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in campaign.campaignproducts.all %}
                            <tr>
                                <td scope="row">{{ forloop.counter }}</td>
                                
                                <td>
                                    <a href="{% url 'product:detail' product.product.pk %}">
                                    {{product.product}}
                                    </a>
                                </td>
                                <td>

                                    <form class="delete" method="post" action="{% url 'crm:campaign:remove_product' product.pk %}" onsubmit="remove(this, event)">{%csrf_token %}

                                            <button type="submit" class="fabutton">
                                            <i class="fa fa-trash"></i>
                                             </button>
                                    </form>
                                   
                                </td>
                                
                            
                            </tr>
                            {% empty %}
                            <tr>

                            <td colspan="3">No Programs/Couurses added yet</td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>

                    <div id="pagination" align="right">
                        {{pagination|safe}}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block jsscript %}

<script>

$(document).ready(function(){
        
    $('form.delete').submit( function (e){
        e.preventDefault()
        e.stopPropagation()
        if(confirm('Confirm Delete')){
            this.submit()
        }
    })


});

</script>

{% endblock jsscript %}