crm/urls.py
from django.conf.urls import include, url
from crm import views, purchase_history, activity, campaign

app_name = "crm"

purchase_history_patterns = ([



    url(r'^student/(?P<pk>[^/]+)/purchase_history/$', purchase_history.purchases, name="purchases"),

], 'purchase_history')

activity_patterns = ([



    url(r'^student/(?P<pk>[^/]+)/activities/$', activity.list, name="list"),

], 'activity')

campaign_patterns = ([

    url(r'^create/$', campaign.campaign_create, name="campaign_create"),
    url(r'^list/$', campaign.campaign_list, name="campaign_list"),
    url(r'^(?P<pk>[^/]+)/detail/$', campaign.campaign_detail, name="campaign_detail"),
    url(r'^(?P<pk>[^/]+)/edit/$', campaign.campaign_edit, name="campaign_edit"),
    # url(r'^(?P<pk>[^/]+)/add_new_vendor/$', campaign.add_vendor, name="add_vendor"),
    # url(r'^(?P<pk>[^/]+)/add_vendor/$', campaign.existing_vendors, name="existing_vendors"),
    # url(r'^(?P<pk>[^/]+)/list_vendors/$', campaign.vendors, name="vendors"),
    # url(r'^vendor/(?P<pk>[^/]+)/remove/$', campaign.remove_vendor, name="remove_vendor"),
    url(r'^(?P<pk>[^/]+)/add_products/$', campaign.add_products, name="add_products"),
    url(r'^(?P<pk>[^/]+)/list_products/$', campaign.products, name="products"),
    url(r'^product/(?P<pk>[^/]+)/remove/$', campaign.remove_product, name="remove_product"),
    url(r'^TargetAudience/(?P<pk>[^/]+)/create/$', campaign.target_audience_create, name="target_audience_create"),
    url(r'^(?P<pk>[^/]+)/add_new_student/$', campaign.add_customer, name="add_customer"),
    url(r'^(?P<pk>[^/]+)/add_student/$', campaign.existing_customers, name="existing_customers"),
    url(r'^(?P<pk>[^/]+)/list_student/$', campaign.customers, name="customers"),
    url(r'^student/(?P<pk>[^/]+)/remove/$', campaign.remove_customer, name="remove_customer"),

], 'campaign')


urlpatterns = [

    url(r'^', include(purchase_history_patterns)),
    url(r'^', include(activity_patterns)),
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    # url(r'^students/$', views.customers, name="customers"),
    url(r'^campaign/', include(campaign_patterns)),
    # url(r'^crm/customers/$', views.customers, name="customers"),
    url(r'^crm/contact/(?P<custm_pk>[^/]+)/paymentDetails/$', views.full_payment_details, name='full_payment_details'),


]

easyLink/urls.py
from django.conf import settings
from django.conf.urls import include, url
"""easyLink URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from sitetree.sitetreeapp import compose_dynamic_tree, register_dynamic_trees
from django.conf.urls.static import static
from erp_admin import views as erpAdminViews

urlpatterns = [
    url(r'^$', erpAdminViews.dashboard),
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('employee.urls', namespace="employee")),
    # url(r'^', include('customer.urls', namespace="customer")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('product.urls', namespace="product")),
    url(r'^crm/', include('crm.urls', namespace="crm")),
    url(r'^', include('enquiry.urls', namespace="enquiry")),
    url(r'^erp_core/', include('erp_core.urls', namespace="erp_core")),
    url(r'^', include('student.urls', namespace="student")),
    url(r'^', include('location.urls', namespace="location")),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
register_dynamic_trees(

    compose_dynamic_tree('erp_admin'),

    # or gather all the trees from `books` and attach them to `main` tree root,
    # compose_dynamic_tree('project'),
    # compose_dynamic_tree('company'),

    # compose_dynamic_tree('gst'),
    compose_dynamic_tree('employee'),
    # compose_dynamic_tree('product'),
    # compose_dynamic_tree('vendor'),
    compose_dynamic_tree('product'),

    # compose_dynamic_tree('inventory'),
    # compose_dynamic_tree('customer'),
    compose_dynamic_tree('enquiry'),
    compose_dynamic_tree('crm'),
    compose_dynamic_tree('student'),


)

enquiry/urls.py
from django.conf.urls import url, include
from enquiry import api, views, mobile_api, enquiry
from rest_framework import routers

# router = routers.DefaultRouter()
# router.register(r'enquiries', api.EnquiryViewSet, base_name="enquiry")

# m_router = routers.DefaultRouter()
# activity_router = routers.DefaultRouter()
# m_router.register(r'enquiries', mobile_api.EnquiryViewSet, base_name="enquiry")
# activity_router.register(r'activities', activity_api.ActivityViewSet, base_name="activities")

# enquiry_list = api.EnquiryViewSet.as_view({'get': 'list'})
# enquiry_create = api.EnquiryViewSet.as_view({'get': 'create_form'})
# enquiry_retrieve = api.EnquiryViewSet.as_view({'get': 'retrieve'})

# activity_list = activity_api.ActivityViewSet.as_view({'get': 'list'})
# activity_detail = activity_api.ActivityViewSet.as_view({'get': 'retrieve'})
# quotation_list = quote.QuotationViewSet.as_view({'get': 'list'})

app_name = "enquiry"

urlpatterns = [
    # url(r'^enquiries/', enquiry_api.enquiry_list, name="enquiry_list"),
    url(r'^enquiries/$', enquiry.list, name="list"),
    url(r'^enquiries/create/$', enquiry.create, name="create"),
    url(r'^enquiries/code_settings/$', views.code_settings, name='code_settings'),
    # url(r'^enquiries/(?P<pk>[^/]+)/$', enquiry_retrieve, name="detail"),
    url(r'^enquiries/(?P<pk>[^/]+)/delete/$', enquiry.delete, name="delete"),
    url(r'^enquiry/(?P<pk>[^/]+)/details/$', enquiry.enquiry_detail, name="enquiry_detail"),
    url(r'^enquiry/(?P<pk>[^/]+)/edit/$', enquiry.edit, name="edit"),
    url(r'^enquiry/activity/(?P<pk>[^/]+)/complete/$', enquiry.complete_activity, name="complete_activity"),
    url(r'^enquiry/(?P<pk>[^/]+)/edit_status/$', enquiry.edit_status, name="edit_status"),
    url(r'^enquiry/(?P<pk>[^/]+)/remark/$', enquiry.add_remark, name="add_remark"),
    url(r'^enquiry/(?P<pk>[^/]+)/onhold/$', enquiry.add_onhold_remark, name="add_onhold_remark"),


    # /enquiries/code_settings/
    # Activity urls
    url(r'^enquiries/(?P<enquiry_pk>[^/]+)/activities/create/$', views.create_activity, name="add_activity"),
    url(r'^activitie/(?P<pk>[^/]+)/edit/$', views.edit_activity, name="edit_activity"),
    url(r'^activitie/(?P<pk>[^/]+)/delete/$', views.delete_activity, name="delete_activity"),
    url(r'^activitie/(?P<pk>[^/]+)/view/$', views.view_activity, name="view_activity"),
    # url(r'^quotations/$', quotation_list, name="quotations"),
    # url(r'^api/', include(router.urls, namespace='api')),
    # url(r'^m/api/', include(m_router.urls, namespace='m-api')),
    # url(r'^api/', include(activity_router.urls, namespace='m-api')),
    # url(r'^quote/', include(router.urls, namespace='quote')),
    url(r'^reports/office/$', enquiry.filter_based_on_office, name="filter_based_on_office"),
    url(r'^reports/streamwise/$', enquiry.stream_wise_report, name="stream_wise_report"),
    url(r'^enquiries/(?P<pk>[^/]+)/activity_type/$', views.create_activity_type, name="create_activity_type"),


]
# GET /m/api/enquiries/ => enquiry list
# GET /m/api/enquiries/choices => enquiry choice fields
# POST /m/api/enquiries/  => create enquiry
# PUT /m/api/enquiries/{pk}  => update enquiry
# DELETE /m/api/enquiries/{pk}  => delete enquiry

student/urls.py
from django.conf.urls import include, url

# from employee import views, api
from student import views

app_name = "student"


urlpatterns = [
    url(r'^student/', include([
        url(r'^$', views.index, name="list"),
        # url(r'^create/$', views.create, name="create"),
        url(r'^create/(?P<pk>[^/]+)$', views.create, name="create"),
        url(r'^edit/(?P<pk>[^/]+)$', views.edit, name="edit"),
        url(r'^delete/(?P<pk>[^/]+)$', views.delete, name="delete"),
        url(r'^detail/(?P<pk>[^/]+)$', views.detail, name="detail"),

    ])),
]

address/models.py
import uuid

from django.db import models
from smart_selects.db_fields import ChainedForeignKey

from erp_core.models import ErpAbstractBaseModel, BaseModel


class Address(BaseModel):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # class Meta:
    #     abstract = True

    addressline1 = models.CharField("Addressline 1", max_length=200, null=True, blank=False)
    addressline2 = models.CharField("Addressline 2", max_length=200, null=True, blank=True)
    area = models.CharField(max_length=100, null=True, blank=True)
    zipcode = models.IntegerField(null=True, blank=True)

    country = models.ForeignKey('location.Country', on_delete=models.CASCADE, null=True, blank=True)

    state = ChainedForeignKey('location.State', chained_field="country", chained_model_field="country", show_all=False,
                              auto_choose=True, sort=True, on_delete=models.CASCADE, null=True, blank=True)

    city = ChainedForeignKey('location.City', chained_field="state", chained_model_field="state",
                             on_delete=models.CASCADE, null=True, blank=True)


class Contact(BaseModel):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    phone = models.CharField("Phone Number", max_length=20)
    alternate_phone = models.CharField("Alternate Phone Number", max_length=20, null=True, blank=True)

student/models.py
from django.db import models
from address.models import Contact, Address
from erp_core.models import ErpAbstractBaseModel, BaseCodeSetting
BaseCodeSetting
from location.models import City
from enquiry.models import Enquiry
from product.models import Program
from crm.models import Campaign

# Create your models here.


class Student(ErpAbstractBaseModel):
    SEX = (
        ('Female', 'Female'),
        ('Male', 'Male'),
    )

    def newCode():
        return StudentCodeSetting.new_code()
    code = models.CharField(max_length=20, default=newCode, unique=True)
    name = models.CharField(max_length=255)
    name_of_college = models.CharField(max_length=100, null=True, blank=True)
    year_of_passout = models.IntegerField(null=True, blank=True)
    photo = models.FileField(upload_to='stud/%Y/%m/%d', blank=True, null=True)
    location = models.ForeignKey(City, null=True, blank=True)
    enquiry = models.OneToOneField(Enquiry, null=True, blank=True, related_name='student')
    course = models.ForeignKey(Program, null=True, blank=True)
    gender = models.CharField(max_length=8, choices=SEX, blank=True, null=True)
    campaign = models.ForeignKey(Campaign, null=True, blank=True)

    def __str__(self):
        return (self.name)

    def save(self, *args, **kwargs):

        if self.code and self.created_at is None:
            StudentCodeSetting.incrementCountIndex()

        return super(Student, self).save(*args, **kwargs)


class AddressForStudent(Address):
    student = models.OneToOneField(Student, on_delete=models.CASCADE, related_name="student_address")

    def __str__(self):
        return str(self.student)


class ContactForStudent(Contact):
    student = models.OneToOneField(Student, on_delete=models.CASCADE, related_name="student_contact")

    def __str__(self):
        return str(self.student)


class StudentCodeSetting(BaseCodeSetting):
    pass

student/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Permission, User
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import F, Q, functions, Value as V
from django.http import HttpResponseRedirect, JsonResponse
from .forms import *
from django.shortcuts import get_object_or_404, render
from guardian.shortcuts import get_objects_for_user
from location.models import *
from django.contrib.auth.models import Group
import datetime
from django.db.models import Sum
from django.contrib import messages
from erp_core.pagination import paginate
from .models import *
from django.utils import timezone
from django.db import IntegrityError, transaction
from student.filters import StudentFilter


    
def create(request, pk):
    
    enquiry = get_object_or_404(Enquiry, pk=pk)
    form2 = StudentForm(request.POST or None, request.FILES or None,initial={'name':enquiry.name_of_candidate,'name_of_college':enquiry.name_of_college,'year_of_passout':enquiry.year_of_passout,'location':enquiry.location,'course':enquiry.course})
    form4 = ContactForStudentForm(request.POST or None,initial={'phone':enquiry.contact_number})
    form3 = AddressForStudentForm(request.POST or None)

    if request.method == "POST":

        if form2.is_valid() and form3.is_valid() and form4.is_valid():
            try:
                with transaction.atomic():
                    student = form2.save(commit=False)
                    student.enquiry = enquiry
                    student.save()
                    address = form3.save(commit=False)
                    address.student = student
                    address.save()
                    contact = form4.save(commit=False)
                    contact.student = student
                    contact.save()

                    messages.add_message(request, messages.SUCCESS, 'Student created Successfully.')
                    return HttpResponseRedirect(reverse('student:detail',args=[student.pk]))

            except IntegrityError:
                messages.add_message(request, messages.ERROR, 'Please try again.some network issues.')
            return HttpResponseRedirect(reverse('student:create'))

    context = {
        'form2': form2,
        'form3': form3,
        'form4': form4,
        'form_url': reverse_lazy('student:create',args=[pk])

    }

    return render(request, 'student/create.html', context)


@login_required
@permission_required('employee.change_employee', raise_exception=True)


def edit(request, pk):
    student = get_object_or_404(Student, code=pk)

    if request.method == "POST":
        form2 = StudentForm(request.POST, request.FILES, instance=student)
        form3 = AddressForStudentForm(request.POST, instance=student.student_address)
        form4 = ContactForStudentForm(request.POST, instance=student.student_contact)

        if form2.is_valid() and form3.is_valid() and form4.is_valid():
            student = form2.save()
            # student.user = user
            address = form3.save(commit=False)
            address.student = student
            address.save()
            contact = form4.save(commit=False)
            contact.student = student
            contact.save()
            return HttpResponseRedirect(reverse('student:detail',args=[student.pk]))

    else:

        form2 = StudentForm(instance=student)
        form3 = AddressForStudentForm(instance=student.student_address)
        form4 = ContactForStudentForm(instance=student.student_contact)

    context = {

        'form2': form2,
        'form3': form3,
        'form4': form4,
        'edit': "edit",
        'form_url': reverse_lazy('student:edit', args=[student.code])

    }

    return render(request, 'student/create.html', context)


# @login_required
# @permission_required('employee.delete_employee', raise_exception=True)
def delete(request, pk):
    if request.method == "POST":
        student = get_object_or_404(Student, code=pk)
        student.delete()
        return HttpResponseRedirect(reverse('student:list'))


# @login_required
# # @permission_required('employee.view_employee_details', raise_exception=True)
def detail(request, pk):
    student = get_object_or_404(Student,pk=pk)
    context = {
    'student': student,

    }
    return render(request, 'student/detail.html',context)

def index(request):
    students = Student.objects.all()
    f = StudentFilter(request.GET, queryset=students)
    students, pagination = paginate(request, queryset=f.qs, per_page=5, default=True)


    context = {
        'students': students,
        'pagination': pagination,
        'filter': f,
    }
    return render(request, "student/index.html", context)

student/templates/student/create.html
{% extends "erp_admin/base.html" %} {% load static %} {% block content %}
<style>
#id_password1,
#id_password2 {
    display: block;
    width: 100%;
    height: 40px;
    padding: 6px 12px;
    mobile_nofont-size: 14px;
    line-height: 1.42857143;
    background-image: none;
    border: 1px solid #ccc;
}

#id_country,
#id_state,
#id_city {
    border: 1px solid #e0e0e0!important;
    padding: 5px 8px!important;
    color: #616161!important;
    width: 100%!important;
    font-size: 0.85em!important;
    font-weight: 300!important;
    height: 40px!important;
    -webkit-appearance: none!important;
    outline: none!important;
    font-family: 'Muli-Regular'!important;
    background: none!important;
    box-shadow: none !important;
}

@media (min-width: 768px) {}

.cl {
    padding-top: 30px;
    padding-bottom: 30px;
    border: 1px solid rgb(234, 234, 234);
    margin-top: 30px;
}
.req{
  color:#FC0404!important;
  font-size:20px!important;
}
</style>
<div class="blank">
    <div class="blank-page">
        <div class="row show-grid">
            <div class="col-sm-12">
                {% if not edit %}
                <h4>Add Student</h4>{% endif %} {% if edit %}
                <h4>Edit Student Details</h4>{% endif %}
                <a href="" class="btn btn-danger pull-right">Cancel</a>
            </div>
        </div>
        <form role="form" class="form-horizontal" method="post" action="{{ form_url }}" enctype="multipart/form-data">
            {% csrf_token %}
             {{form2.non_field_errors}}
             {{form3.non_field_errors}}
             {{form4.non_field_errors}}
           
            <div class="panel-body cl">
                <h2>Personal Details</h2>
                <div class="form-group {% if form1.first_name.errors %} has-error{% elif form1.is_bound %} has-success{% endif %}" style="margin-top:30px;">
                    <label class="col-md-2 control-label">Code <span class="req">*</span></label>
                    <div class="col-md-8">
                        {{ form2.code.errors }}{{ form2.code }}
                    </div>
                </div>
                
         
                <div class="form-group {% if form1.first_name.errors %} has-error{% elif form1.is_bound %} has-success{% endif %}" style="margin-top:30px;">
                    <label class="col-md-2 control-label">Name <span class="req">*</span></label>
                    <div class="col-md-8">
                        {{ form2.fname.errors }}{{ form2.name }}
                    </div>
                </div>
                <div class="form-group {% if form1.first_name.errors %} has-error{% elif form1.is_bound %} has-success{% endif %}" style="margin-top:30px;">
                    <label class="col-md-2 control-label">Gender <span class="req">*</span></label>
                    <div class="col-md-8">
                        {{ form2.gender.errors }}{{ form2.gender }}
                    </div>
                </div>
                
                <div class="form-group {% if form2.languages_known.errors %} has-error{% elif form2.is_bound %} has-success{% endif %}">
                    <label class="col-md-2 control-label">{{ form2.name_of_college.label}}<span class="req">*</span></label>
                    <div class="col-md-8">
                        {{ form2.name_of_college.errors }}{{ form2.name_of_college }}
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="form-inline {% if form2.dob.errors %} has-error{% elif form2.is_bound %} has-success{% endif %}">
                        <label class="col-md-2 control-label">{{ form2.year_of_passout.label}}<span class="req">*</span></label>
                        <div class="col-md-3">
                            {{ form2.year_of_passout.errors }}{{ form2.year_of_passout }}
                        </div>
                    </div>
                    <div class="form-inline {% if form2.gender.errors %} has-error{% elif form2.is_bound %} has-success{% endif %}">
                        <label class="col-md-2 control-label">{{ form2.location.label}}<span class="req">*</span></label>
                        <div class="col-md-3">
                            {{ form2.location.errors }}{{ form2.location }}
                        </div>
                    </div>
                    
                </div>
      
                <div class="form-group">
                    <div class="form-inline {% if form2.gender.errors %} has-error{% elif form2.is_bound %} has-success{% endif %}">
                        <label class="col-md-2 control-label">{{ form2.course.label}}<span class="req">*</span></label>
                        <div class="col-md-3">
                            {{ form2.course.errors }}{{ form2.course }}
                        </div>
                    </div>
                    
                    <div class="form-inline {% if form2.photo.errors %} has-error{% elif form2.is_bound %} has-success{% endif %}">
                        <label class="col-md-2 control-label">{{ form2.photo.label}}</label>
                        <div class="col-md-3">
                            {{ form2.photo.errors }}{{ form2.photo }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-body cl">
           
                <h2>Contact Details</h2>
                <div class="form-group {% if form3.addressline1.errors %} has-error{% elif form3.is_bound %} has-success{% endif %}" style="margin-top:30px;">
                    <label class="col-md-2 control-label">{{ form3.addressline1.label}}<span class="req">*</span></label>
                    <div class="col-md-8">
                        {{ form3.addressline1.errors }}{{ form3.addressline1 }}
                    </div>
                </div>
                <div class="form-group {% if form3.addressline2.errors %} has-error{% elif form3.is_bound %} has-success{% endif %}">
                    <label class="col-md-2 control-label">{{ form3.addressline2.label}}<span class="req"></span></label>
                    <div class="col-md-8">
                        {{ form3.addressline2.errors }}{{ form3.addressline2 }}
                    </div>
                </div>
                <div class="form-group {% if form3.area.errors %} has-error{% elif form3.is_bound %} has-success{% endif %}">
                    <label class="col-md-2 control-label">{{ form3.area.label}}<span class="req"></span></label>
                    <div class="col-md-8">
                        {{ form3.area.errors }}{{ form3.area }}
                    </div>

                </div>
                <div class="form-group {% if form3.country.errors %} has-error{% elif form3.is_bound %} has-success{% endif %}">
                    <label class="col-md-2 control-label">{{ form3.country.label}}<span class="req"></span></label>
                    <div class="col-md-8">
                        {{ form3.country.errors }}{{ form3.country }}
                    </div>
                </div>
                <div class="form-group {% if form3.state.errors %} has-error{% elif form3.is_bound %} has-success{% endif %}">
                    <label class="col-md-2 control-label">{{ form3.state.label}}<span class="req"></span></label>
                    <div class="col-md-8">
                        {{ form3.state.errors }}{{ form3.state }}
                    </div>
                </div>
                <div class="form-group {% if form3.city.errors %} has-error{% elif form3.is_bound %} has-success{% endif %}">
                    <label class="col-md-2 control-label">{{ form3.city.label}}<span class="req"></span></label>
                    <div class="col-md-8">
                        {{ form3.city.errors }}{{ form3.city }}
                    </div>
                </div>
                <div class="form-group {% if form3.zipcode.errors %} has-error{% elif form3.is_bound %} has-success{% endif %}">
                    <label class="col-md-2 control-label">{{ form3.zipcode.label}}<span class="req"></span></label>
                    <div class="col-md-8">
                         {{ form3.zipcode.errors }}{{ form3.zipcode }}
                    </div>
                </div>
                <div class="form-group">

                    <div class="form-inline {% if form4.phone.errors %} has-error{% elif form4.is_bound %} has-success{% endif %}">
                        <label class="col-md-2 control-label">{{ form4.phone.label}}<span class="req">*</span></label>
                        <div class="col-md-3">
                            {{ form4.phone.errors }}{{ form4.phone }}
                        </div>
                    </div>
                    <div class="form-inline {% if form4.alternate_phone.errors %} has-error{% elif form4.is_bound %} has-success{% endif %}">
                        <label class="col-md-2 control-label">{{ form4.alternate_phone.label}}<span class="req"></span></label>
                        <div class="col-md-3">
                            {{ form4.alternate_phone.errors }}{{ form4.alternate_phone }}
                    </div>
                    </div>
                </div>
            </div>

            <div class="panel-body cl">
               
                <h2>Campaign Details</h2>
                   
                    <div class="form-group" style="padding-top:2%;">

                        <div class="form-inline {% if form2.campaign.errors %} has-error{% elif form2.is_bound %} has-success{% endif %}">
                            <label class="col-md-2 control-label">{{form2.campaign.label}}<span class="req"></span></label>
                            <div class="col-md-3">
                                {{ form2.campaign.errors }}{{form2.campaign }}
                            </div>
                        </div>
                        
                    </div>
                    <button type="submit" class="btn btn-primary pull-right">Submit</button>
                </div>
            
        </form>
    </div>
</div>
{% endblock content %} {% block jsscript %}
<!-- <script src="{% static 'js/jquery.auto-complete.js' %}"></script>
<script src="{% static 'js/office_search.js' %}"></script>
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script> -->
<script>
$("#id_location").select2({
    maximumSelectionLength: 10,
    allowClear: true,
    placeholder: "Select Location",


});
$("#id_course").select2({
    maximumSelectionLength: 10,
    allowClear: true,
    placeholder: "Select Course",


});
$("#id_campaign").select2({
    maximumSelectionLength: 10,
    allowClear: true,
    placeholder: "Select Campaign",


})
</script>

{% endblock jsscript %}