crm/urls.py
from django.conf.urls import include, url
from crm import views, purchase_history, activity, campaign

app_name = "crm"

purchase_history_patterns = ([



    url(r'^student/(?P<pk>[^/]+)/purchase_history/$', purchase_history.purchases, name="purchases"),

], 'purchase_history')

activity_patterns = ([



    url(r'^student/(?P<pk>[^/]+)/activities/$', activity.list, name="list"),

], 'activity')

campaign_patterns = ([

    url(r'^create/$', campaign.campaign_create, name="campaign_create"),
    url(r'^list/$', campaign.campaign_list, name="campaign_list"),
    url(r'^(?P<pk>[^/]+)/detail/$', campaign.campaign_detail, name="campaign_detail"),
    url(r'^(?P<pk>[^/]+)/edit/$', campaign.campaign_edit, name="campaign_edit"),
    # url(r'^(?P<pk>[^/]+)/add_new_vendor/$', campaign.add_vendor, name="add_vendor"),
    # url(r'^(?P<pk>[^/]+)/add_vendor/$', campaign.existing_vendors, name="existing_vendors"),
    # url(r'^(?P<pk>[^/]+)/list_vendors/$', campaign.vendors, name="vendors"),
    # url(r'^vendor/(?P<pk>[^/]+)/remove/$', campaign.remove_vendor, name="remove_vendor"),
    url(r'^(?P<pk>[^/]+)/add_products/$', campaign.add_products, name="add_products"),
    url(r'^(?P<pk>[^/]+)/list_products/$', campaign.products, name="products"),
    url(r'^product/(?P<pk>[^/]+)/remove/$', campaign.remove_product, name="remove_product"),
    url(r'^TargetAudience/(?P<pk>[^/]+)/create/$', campaign.target_audience_create, name="target_audience_create"),
    url(r'^(?P<pk>[^/]+)/add_new_student/$', campaign.add_customer, name="add_customer"),
    url(r'^(?P<pk>[^/]+)/add_student/$', campaign.existing_customers, name="existing_customers"),
    url(r'^(?P<pk>[^/]+)/list_student/$', campaign.customers, name="customers"),
    url(r'^student/(?P<pk>[^/]+)/remove/$', campaign.remove_customer, name="remove_customer"),

], 'campaign')


urlpatterns = [

    url(r'^', include(purchase_history_patterns)),
    url(r'^', include(activity_patterns)),
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    # url(r'^students/$', views.customers, name="customers"),
    url(r'^campaign/', include(campaign_patterns)),
    # url(r'^crm/customers/$', views.customers, name="customers"),
    url(r'^crm/contact/(?P<custm_pk>[^/]+)/paymentDetails/$', views.full_payment_details, name='full_payment_details'),


]

easyLink/urls.py
from django.conf import settings
from django.conf.urls import include, url
"""easyLink URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from sitetree.sitetreeapp import compose_dynamic_tree, register_dynamic_trees
from django.conf.urls.static import static
from erp_admin import views as erpAdminViews

urlpatterns = [
    url(r'^$', erpAdminViews.dashboard),
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('employee.urls', namespace="employee")),
    # url(r'^', include('customer.urls', namespace="customer")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('product.urls', namespace="product")),
    url(r'^crm/', include('crm.urls', namespace="crm")),
    url(r'^', include('enquiry.urls', namespace="enquiry")),
    url(r'^erp_core/', include('erp_core.urls', namespace="erp_core")),
    url(r'^', include('student.urls', namespace="student")),
    url(r'^', include('location.urls', namespace="location")),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
register_dynamic_trees(

    compose_dynamic_tree('erp_admin'),

    # or gather all the trees from `books` and attach them to `main` tree root,
    # compose_dynamic_tree('project'),
    # compose_dynamic_tree('company'),

    # compose_dynamic_tree('gst'),
    compose_dynamic_tree('employee'),
    # compose_dynamic_tree('product'),
    # compose_dynamic_tree('vendor'),
    compose_dynamic_tree('product'),

    # compose_dynamic_tree('inventory'),
    # compose_dynamic_tree('customer'),
    compose_dynamic_tree('enquiry'),
    compose_dynamic_tree('crm'),
    compose_dynamic_tree('student'),


)

employee/urls.py
from django.conf.urls import include, url

# from employee import views, api
from employee import views

app_name = "employee"


urlpatterns = [
    url(r'^employee/', include([
        url(r'^$', views.index, name="list"),
        url(r'^select_list/$', views.select2_list, name="select_list"),
        url(r'^select_employee/$', views.select_employee, name="select_employee"),
        url(r'^select_designation/$', views.select_designation, name="select_designation"),
        url(r'^create/$', views.create, name='create'),
        url(r'^(?P<pk>[^/]+)/edit/', views.edit, name='edit'),
        url(r'^(?P<pk>[^/]+)/delete/', views.delete, name='delete'),
        url(r'^(?P<pk>[^/]+)/profile/', views.profile, name='profile'),
        url(r'^incentive/list/$', views.incentive_list, name='incentive_list'),
        url(r'^incentive/list/(?P<from_date>[-\w]+)/(?P<to_date>[-\w]+)/$', views.incentive_list, name="incentiveList"),
        # url(r'^(?P<pk>[^/]+)/incentive/$', views.incentives, name='incentives'),
        # url(r'^(?P<pk>[^/]+)/incentive/(?P<from_date>[-\w]+)/(?P<to_date>[-\w]+)/$', views.incentives, name="incentives"),
        # url(r'^findoffice/', views.select_office, name="select_office"),
        # url(r'^(?P<employee_pk>[^/]+)/todo/', include('todo.urls', namespace="todo")),
        url(r'^(?P<pk>[^/]+)/addtargets/', views.add_targets, name='add_targets'),
        url(r'^(?P<pk>[^/]+)/targets/', views.view_targets, name='view_targets'),
        url(r'^(?P<pk>[^/]+)/editTarget/(?P<target_pk>[^/]+)/$', views.edit_targets, name='edit_targets'),
        url(r'^employee/(?P<pk>[^/]+)/target/(?P<target_pk>[^/]+)/delete/$', views.delete_targets, name='delete_targets'),
        # # url(r'^batterystatus/create/$', api.CreateBatteryStatus, name="CreateBatteryStatus"),
        # url(r'^(?P<pk>[^/]+)/timesheet/(?P<from_date>[-\w]+)/(?P<to_date>[-\w]+)/$', views.timesheet, name='timesheet_withdate'),
        # url(r'^(?P<pk>[^/]+)/timesheet/', views.timesheet, name='timesheet'),
        # url(r'^(?P<pk>[^/]+)/report/$', views.my_report, name="my_report"),
        # url(r'^(?P<pk>[^/]+)/report/(?P<from_date>[-\w]+)/(?P<to_date>[-\w]+)/$',
        #     views.my_report, name="my_report_with_range"),
        url(r'^incentive/list/(?P<from_date>[-\w]+)/(?P<to_date>[-\w]+)/$', views.incentive_list, name="incentiveList"),
        url(r'^incentives/(?P<pk>[^/]+)/$', views.employee_incentives, name="employee_incentives"),
        url(r'^(?P<pk>[^/]+)/performance/report/$', views.performance_report, name="performance_report"),
        url(r'^(?P<pk>[^/]+)/payout/$', views.request_for_payout, name="request_for_payout"),
        url(r'^all/incentives/(?P<pk>[^/]+)/$', views.all_incentives, name="all_incentives"),
        url(r'^(?P<pk>[^/]+)/incentive/(?P<incentive_pk>[^/]+)/approve/$',
            views.approve_incentive, name="approve_incentive"),





    ])),
    url(r'^incentive_slabs/$', views.incentiveslab_list, name="slab_list"),
    url(r'^incentive_slab/add/$', views.add_slab, name="add_slab"),
    url(r'^incentive_slab/edit/(?P<pk>[^/]+)/$', views.edit_slab, name="edit_slab"),
    url(r'^incentive_slab/delete/(?P<pk>[^/]+)/$', views.delete_slab, name="delete_slab"),


]

employee/models.py
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from address.models import *
from company.models import *
from erp_core.models import ErpAbstractBaseModel
from django.core.validators import MinValueValidator


class AddressForEmployee(Address):
    employee = models.OneToOneField(
        'Employee', on_delete=models.CASCADE, related_name="employee_address")

    def __str__(self):
        return str(self.employee)


class ContactForEmployee(Contact):
    employee = models.OneToOneField(
        'Employee', on_delete=models.CASCADE, related_name="employee_contact")

    def __str__(self):
        return str(self.employee)


class Employee(ErpAbstractBaseModel):
    SEX = (
        ('Female', 'Female'),
        ('Male', 'Male'),
    )

    MARITALSTATUS = (
        ('Single', 'Single'),
        ('Married', 'Married'),
    )

    BLOODGROUP = (
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
    )
    code = models.CharField(max_length=255, unique=True)
    photo = models.FileField(upload_to='prof/%Y/%m/%d', blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=8, choices=SEX, blank=True, null=True)
    marital_status = models.CharField(max_length=10, choices=MARITALSTATUS, blank=True, null=True)
    blood_group = models.CharField(max_length=3, choices=BLOODGROUP, blank=True, null=True)
    languages_known = models.CharField(max_length=255, blank=True, null=True)
    birth_place = models.CharField(max_length=100, blank=True, null=True)
    cast = models.CharField(max_length=100, null=True, blank=True)
    religion = models.CharField(max_length=100, null=True, blank=True)
    citizenship = models.CharField(max_length=100, blank=True, null=True)
    status = models.BooleanField(default=True)

    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)

    primary_designation = models.ForeignKey(
        Designation, on_delete=models.CASCADE)

    secondary_designation = models.ManyToManyField(
        Designation, related_name="employee_secondary_designation", blank=True)

    reporting_officer = models.ForeignKey(
        'employee.Employee', on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        permissions = (
            ("view_employee_list", "Can view employee list"),
            ("view_employee_details", "Can view employee details"),
            ("can_access", "Can access Employee Section"),
            ("reporting_officier", "I am a reporting officier"),
            ("is_support", "Support")
        )

    def get_absolute_url(self):
        return reverse('employee:profile', args=[self.code])

    def __str__(self):
        return str(self.user.first_name) + " (" + str(self.code) + ")"


class EmployeeCode(ErpAbstractBaseModel):

    character_set = models.CharField(max_length=100)


class Targets(ErpAbstractBaseModel):
    amount = models.IntegerField(default=0, verbose_name="Target")
    employee = models.ForeignKey(Employee)
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)
    incentive_amount = models.DecimalField(
        max_digits=200, decimal_places=2, null=True, blank=True, validators=[MinValueValidator(0)])
    percentage = models.IntegerField(default=0, validators=[MinValueValidator(0)])

    def __str__(self):
        return str(self.employee) + "-" + " from " + str(self.from_date) + " to " + str(self.to_date)

    # class Meta:
    #     unique_together = ("from_date", "to_date")

    # def unique_error_message(self, model_class, unique_check):
    #     print(model_class)
    #     import pdb; pdb.set_trace()
    #     if model_class == type(self) and unique_check == ("employee", "from_date", "to_date"):
    #         return 'My custom error message'
    #     else:
    #         return super(Targets, self).unique_error_message(model_class, unique_check)

# class Incentive(ErpAbstractBaseModel):
#     target = models.OneToOneField(Targets,related_name='target_incentive')
#     def __str__(self):
#         return str(self.target)


# class Batterystatus(ErpAbstractBaseModel):
#     employee = models.ForeignKey(Employee)
#     date_and_time = models.DateTimeField()
#     level = models.PositiveIntegerField()
#
#     def __str__(self):
#         return str(self.employee)


# class Bonus(ErpAbstractBaseModel):
#     name = models.CharField(max_length=255, unique=True)
#     amount = models.DecimalField(max_digits=20, decimal_places=2, validators=[MinValueValidator(0)])
#
#     def __str__(self):
#         return str(self.name)


# class DistanceTraveled(models.Model):
#     distance = models.IntegerField(default=0, validators=[MinValueValidator(0)])
#     date = models.DateField()
#     employee = models.ForeignKey(Employee)
#
#     class Meta:
#         unique_together = ("date", "employee")
#
#     def __str__(self):
#         return str(self.employee)


class IncentiveSlab(ErpAbstractBaseModel):
    PARTNER = 'partner'
    COUNSELLOR = 'counselor'
    TYPES = (
        (PARTNER, "partner"),
        (COUNSELLOR, "counselor"),
    )

    start_value = models.IntegerField()
    end_value = models.IntegerField()
    employee_type = models.CharField(max_length=20, choices=TYPES, default=COUNSELLOR)
    amount = models.IntegerField()

    def __str__(self):
        return str(self.amount)


class EmployeePayout(ErpAbstractBaseModel):
    REQUESTED = 'requested'
    NOTREQUESTED = 'not requested'
    APPROVED = 'approved'
    STATUS = (
        (REQUESTED, "requested"),
        (NOTREQUESTED, "not requested"),
        (APPROVED, "approved"),
    )
    employee = models.ForeignKey(Employee, related_name="payout")
    request_date = models.DateField()
    pay_out_date = models.DateField(null=True, blank=True)
    approved_by = models.ForeignKey(Employee, related_name="payout_approved_by", null=True, blank=True)
    amount = models.DecimalField(max_digits=50, decimal_places=4)
    status = models.CharField(max_length=20, choices=STATUS, default=NOTREQUESTED)

    def __str__(self):
        return str(self.employee)

    class Meta:
        unique_together = ("employee", "request_date")

employee/templates/employee/index.html
{% extends "erp_admin/base.html" %} {% load guardian_tags %} {% block content %}
<div class="blank">
    <div class="blank-page">
        <div class="row show-grid">
            <div class="col-sm-12">
                <h2>
                    Employees
                    <a href="{% url 'employee:create' %}" class="btn btn-link">
                     <i class="fa fa-plus-square-o fa-2x"></i>
                    </a>
                </h2>
                <!--
                    {% if request.user.is_staff %}<a href="{% url 'employee:slab_list' %}" class="btn btn-success pull-right">Set Incentive Slabs</a>{% endif %}
                -->
               

                <!--<a href="{% url 'employee:incentive_list' %}" class="btn btn-success pull-right">Incentive List</a>-->


            </div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-12 table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Code</th>
                            <th>Name</th>
                            <th></th>
                            <th></th>
                            
                            
                        </tr>
                    </thead>
                    <tbody>
                        {% for employee in employees %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>
                              <a href="{% url 'employee:profile' employee.code %}">
                               {{employee.code}}
                               </a>
                            </td>
                            <td>
                                {{employee.user.first_name}}
                            </td>
                            
                            
                            {% if perms.employee.change_employee %}
                            <td>
                                 <a href="{% url 'employee:edit' employee.code %}" class="pull-right">
                                <i class="fa fa-edit"></i>
                                </a>
                            </td>
                            {% endif %}
                            {% if perms.employee.delete_employee %}
                            <td>
                                 <a href="{% url 'employee:delete' employee.code %}" class="pull-right">
                                <i class="fa fa-trash-o"></i>
                                </a>
                            </td>
                            {% endif %}
                        </tr>

                        {% empty %}
                        <tr>
                            <td colspan="4">No Employees in System</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

employee/templates/employee/profile.html
{% extends "erp_admin/base.html" %}
{% block title %} Profile{% endblock title %}
{% block content %}
<style>
.btn{
text-align: left!important;
}
.cl{
padding:30px;
border: 1px solid rgb(234, 234, 234);
margin-left:3px;
}
.cl1{
padding:20px;
border: 1px solid rgb(234, 234, 234);
margin-left:20px;
margin-right:20px;
margin-top:0px!important;
}
.profile-bottom{
width:100%!important;
margin-bottom:0px!important;
}
.profile {
min-height: 430px!important;
}
</style>
<div class="blank">
    <div class="blank-page">
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <h2></h2>
                {% if request.user.is_staff %}<a href="{% url 'employee:list' %}" >Back</a>{% endif %}
            </div>
            <!-- Example split danger button -->

            <div class="col-xs-12 col-sm-3 pull-right">
                <!--<div class="dropdown">
                    <button id="dLabel" class="btn btn-primary" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     View More
                    <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dLabel"> 
                        <li>
                            <a href="" class="btn btn-link"> </a>
                                
                        </li>
                       
                        <li> 
                            <a href="{% url 'employee:add_targets' employee.pk %}" class="btn btn-link"> 
                                 Add Target 
                            </a>
                        </li> 
                    
                        <li> 
                            <a href="{% url 'employee:view_targets' employee.pk %}" class="btn btn-link"> 
                               View Target 
                            </a> 
                         </li> 
                    </ul> 
                    
                </div>-->
            </div>
        </div>
        <div class="profile">
            <div class="profile-bottom">
                <h3><i class="fa fa-user"></i>Profile</h3>
                <div class="profile-bottom-top">
                    <div class="col-md-4 profile-bottom-img">
                        {% if employee.photo %}<img src="{{employee.photo.url}}" width="130px" height="130px">{% endif %}
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-8 profile-text">
                        <h6>{{employee.user.first_name}}</h6>
                        <table class="col-xs-12">
                            <tr><td>Employee Code:
                                <!-- <td>:</td> -->
                            {{employee.code}}</td>
                        </tr>
                        <tr><td>Designation :
                            <!-- <td>:</td> -->
                        {{employee.primary_designation.name }}</td>
                    </tr>
                    
                    <tr>
                        <td>Email :
                            <!-- <td> :</td> -->
                            <a href="{{employee.user.email}}">{{employee.user.email}}</a>
                        </td>
                    </tr>
                    <tr>
                        <td>Country :
                            <!-- <td>:</td> -->
                            {{employee.employee_address.country.name}}
                        </tr>
                    </table>
                    {% if request.user.is_staff %}
                        <a href="{% url 'employee:edit' employee.code %}" class="btn bg-success pull-right">Edit Profile</a>
                    {% endif %}
                </div>
                <div class="clearfix"></div>
            </div>
            
            
            
            
        </div>
    </div>
    <div class="row cl1">
        <div class="">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse1"><h3>Personal Details</h3></a>
                            </h4>
                        </div>
                        <div id="collapse1" class="panel-collapse collapse">
                            <div class="panel-body">Date Of Birth :{{employee.dob|date:'d M Y'}}</div>
                            {% if employee.gender %}
                                <div class="panel-body">Gender : {{employee.gender}}</div>
                            {% endif %}
                            {% if employee.marital_status %}
                            <div class="panel-body">Marital Status : {{employee.marital_status}}</div>
                            {% endif %}
                            {% if employee.blood_group %}
                            <div class="panel-body">Blood Group : {{employee.blood_group}}</div>
                            {% endif %}
                            {% if employee.languages_known %}
                            <div class="panel-body">Languages known : {{employee.languages_known}}</div>
                            {% endif %}
                            <!--<div class="panel-body">Birth Place : {{employee.birth_place}}</div>-->
                            <!--<div class="panel-body">Cast : {{employee.cast}}</div>
                            <div class="panel-body">Religion : {{employee.religion}}</div>-->
                             {% if employee.citizenship %}
                            <div class="panel-body">Citizenship : {{employee.citizenship}}</div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                
            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse2"><h3>Contact Details</h3></a>
                            </h4>
                        </div>
                        <div id="collapse2" class="panel-collapse collapse">
                            <div class="panel-body">
                                Contact Address
                            </div>
                            <div class="panel-body">
                                <address>
                                    {{employee.employee_address.addressline1}},
                                    {% if employee.employee_address.addressline2 %}
                                    {{employee.employee_address.addressline2}}</br>
                                    {% endif %}
                                    {% if employee.employee_address.area %}
                                    {{employee.employee_address.area}}
                                    {% endif %}
                                    {% if employee.employee_address.city %}
                                    {{employee.employee_address.city}}</br>
                                    {% endif %}
                                    {% if employee.employee_address.state %}
                                    {{employee.employee_address.state}}</br>
                                    {% endif %}
                                    {% if employee.employee_address.country %}
                                    {{employee.employee_address.country}}-
                                    {% endif %}
                                    {% if employee.employee_address.zipcode %}
                                     {{employee.employee_address.zipcode}}
                                    {% endif %}
                                </address>
                            </div>
                            <div class="panel-body">
                                Phone Number : {{employee.employee_contact.phone}}
                            </div>
                            <div class="panel-body">
                                {% if employee_contact.alternate_phone %} 
                                Alternate Phone Number : {{employee.employee_contact.alternate_phone}}
                                {% endif %}
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse3"><h3>Company Details</h3></a>
                            </h4>
                        </div>
                        <div id="collapse3" class="panel-collapse collapse">
                            <div class="panel-body">Office Address :  </div>
                            {% if employee.primary_designation.location.name %}
                            <div class="panel-body">Location : {{employee.primary_designation.location.name}}</div>
                            {% endif %}
                            {% if employee.primary_designation.office.name %}
                            <div class="panel-body">Office : {{employee.primary_designation.office.name}}</div>
                            {% endif %}
                            {% if employee.primary_designation.department.name %}
                            <div class="panel-body">Department : {{employee.primary_designation.department.name}}</div>
                            {% endif %}
                            {% if employee.primary_designation.division.name %}
                            <div class="panel-body">Division : {{employee.primary_designation.division.name}}</div>
                            {% endif %}
                            
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse4"><h3>Designation & Reporting Officer</h3></a>
                            </h4>
                        </div>
                        <div id="collapse4" class="panel-collapse collapse">
                            
                            <div class="panel-body">Primary Designation : {{employee.primary_designation.name}}</div>
                            
                            <div class="panel-body">
                            {% if employee.reporting_officer.user.first_name %}

                                Reporting Officer : {{employee.reporting_officer.user.first_name}} &nbsp;{{employee.reporting_officer.user.last_name}}-
                            
                            {{employee.reporting_officer.primary_designation.name}}
                            {% endif %}
                        </div>
                            
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
        
    </div>
</div>
{% endblock content %}

employee/templates/employee/view_incentives.html
{% extends "erp_admin/base.html" %} {% load guardian_tags %} {% block content %}
{% load staticfiles %}
{% block head %}
<style>
.border-style{
    border:2px;
    box-shadow:1px;
    
}
</style>
{% endblock head %}
<div class="blank">
    <div class="blank-page">
        <div class="row show-grid" style="margin-bottom:300px;">
            <div class="col-sm-6 col-md-6 col-xs-6">
                <a href="{% url 'employee:list'%}">Back</a>
            </div>
            <div class="col-sm-6 col-md-6 col-xs-6" align="right">
            <a href="{% url 'employee:all_incentives' employee.pk %}" class="btn btn-primary"> Requested Incentives<i class="fa fa-arrow-right"></i></a>
            </div>
            
               

                <div class="row" style="">
                    <div class="col-sm-12 col-md-12 col-xs-12">
                        <div class="well">
                           <h3>Incentive Details <i class="fa fa-gift" aria-hidden="true"></i></h3>
                        
                            <hr>

                                
                                 <p style="color:#000;"><strong> Name : </strong> {{employee.user.first_name}}</p>
                                 <p style="color:#000;"><strong> Month & Year : </strong> {{date|date:"M/Y"}}</p>
                                 <p style="color:#000;"><strong> No.Of  Leads : </strong>{{enquiries}}</p>
                                  <p style="color:#000;"><strong> Total Amount  : </strong> {{credit}}</p>
                                 
                            <hr>
                        
                            
                        </div>
                     
                    </div>
                    
                   
                </div>
                {% if credit > 0 %}
                {% if request.user.employee == employee %}
                <div class="row">
                   
                    <div class="col-sm-12 col-md-12 col-xs-12">

                            {% if pay_out != 0 %}
                            <a class="btn btn-success pull-right">
                            <i class="fa fa-check"></i>
                            {{pay_out.status|title}}</a>
                            {% else %}
                            <a href="{% url 'employee:request_for_payout' employee.pk %}" class="btn btn-success pull-right">
                            Request for Payout <i class="fa fa-arrow-right"></i></a>
                            {% endif %}
                    </div>
                   
                </div>
                {% endif %}
                {% endif %}
                
          </div>

        </div>
    </div>
</div>
        
   

{% endblock content %}