crm/urls.py
from django.conf.urls import include, url
from crm import views, purchase_history, activity, campaign

app_name = "crm"

purchase_history_patterns = ([



    url(r'^student/(?P<pk>[^/]+)/purchase_history/$', purchase_history.purchases, name="purchases"),

], 'purchase_history')

activity_patterns = ([



    url(r'^student/(?P<pk>[^/]+)/activities/$', activity.list, name="list"),

], 'activity')

campaign_patterns = ([

    url(r'^create/$', campaign.campaign_create, name="campaign_create"),
    url(r'^list/$', campaign.campaign_list, name="campaign_list"),
    url(r'^(?P<pk>[^/]+)/detail/$', campaign.campaign_detail, name="campaign_detail"),
    url(r'^(?P<pk>[^/]+)/edit/$', campaign.campaign_edit, name="campaign_edit"),
    # url(r'^(?P<pk>[^/]+)/add_new_vendor/$', campaign.add_vendor, name="add_vendor"),
    # url(r'^(?P<pk>[^/]+)/add_vendor/$', campaign.existing_vendors, name="existing_vendors"),
    # url(r'^(?P<pk>[^/]+)/list_vendors/$', campaign.vendors, name="vendors"),
    # url(r'^vendor/(?P<pk>[^/]+)/remove/$', campaign.remove_vendor, name="remove_vendor"),
    url(r'^(?P<pk>[^/]+)/add_products/$', campaign.add_products, name="add_products"),
    url(r'^(?P<pk>[^/]+)/list_products/$', campaign.products, name="products"),
    url(r'^product/(?P<pk>[^/]+)/remove/$', campaign.remove_product, name="remove_product"),
    url(r'^TargetAudience/(?P<pk>[^/]+)/create/$', campaign.target_audience_create, name="target_audience_create"),
    url(r'^(?P<pk>[^/]+)/add_new_student/$', campaign.add_customer, name="add_customer"),
    url(r'^(?P<pk>[^/]+)/add_student/$', campaign.existing_customers, name="existing_customers"),
    url(r'^(?P<pk>[^/]+)/list_student/$', campaign.customers, name="customers"),
    url(r'^student/(?P<pk>[^/]+)/remove/$', campaign.remove_customer, name="remove_customer"),

], 'campaign')


urlpatterns = [

    url(r'^', include(purchase_history_patterns)),
    url(r'^', include(activity_patterns)),
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    # url(r'^students/$', views.customers, name="customers"),
    url(r'^campaign/', include(campaign_patterns)),
    # url(r'^crm/customers/$', views.customers, name="customers"),
    url(r'^crm/contact/(?P<custm_pk>[^/]+)/paymentDetails/$', views.full_payment_details, name='full_payment_details'),


]

easyLink/urls.py
from django.conf import settings
from django.conf.urls import include, url
"""easyLink URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from sitetree.sitetreeapp import compose_dynamic_tree, register_dynamic_trees
from django.conf.urls.static import static
from erp_admin import views as erpAdminViews

urlpatterns = [
    url(r'^$', erpAdminViews.dashboard),
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('employee.urls', namespace="employee")),
    # url(r'^', include('customer.urls', namespace="customer")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('product.urls', namespace="product")),
    url(r'^crm/', include('crm.urls', namespace="crm")),
    url(r'^', include('enquiry.urls', namespace="enquiry")),
    url(r'^erp_core/', include('erp_core.urls', namespace="erp_core")),
    url(r'^', include('student.urls', namespace="student")),
    url(r'^', include('location.urls', namespace="location")),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
register_dynamic_trees(

    compose_dynamic_tree('erp_admin'),

    # or gather all the trees from `books` and attach them to `main` tree root,
    # compose_dynamic_tree('project'),
    # compose_dynamic_tree('company'),

    # compose_dynamic_tree('gst'),
    compose_dynamic_tree('employee'),
    # compose_dynamic_tree('product'),
    # compose_dynamic_tree('vendor'),
    compose_dynamic_tree('product'),

    # compose_dynamic_tree('inventory'),
    # compose_dynamic_tree('customer'),
    compose_dynamic_tree('enquiry'),
    compose_dynamic_tree('crm'),
    compose_dynamic_tree('student'),


)

product/urls.py
from django.conf.urls import include, url
from product import api, views

app_name = "product"

# api_patterns = ([

#     # url(r'^invoices/$', api.invoices, name="invoices"),
#     url(r'^products/$', api.ProductList.as_view()),

#     # url(r'^invoice/(?P<code>[^/]+)/payments/$', api.payment_details, name="payment_details"),

# ], 'api')


urlpatterns = [
    # url(r'^api/', include([
    #     # router.urls,
    #     url(r'^products/', include([
    #         url(r'^select_list/$', api.product_select_options, name="select_list"),
    #     ])),
    #     # get active products -api
    #     # url(r'^products/$', api.all_products, name="all_products"),

    # ], namespace='api')),
    url(r'^programs/add_program/$', views.add_products, name='add_products'),
    url(r'^programs/listProgram/$', views.view_products, name='view_products'),
    url(r'^programs/(?P<pk>[^/]+)/detail/$', views.detail, name='detail'),
    url(r'^programs/edit_program/(?P<product_pk>[^/]+)/$',
        views.edit_product, name='edit_product'),
    url(r'^programs/code/settings/$', views.code_settings, name='code_settings'),
    url(r'^programs/(?P<pk>[^/]+)/delete/$', views.delete, name='delete'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # url(r'^import/$', views.import_data, name="import"),


]

product/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Permission, User
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import F, Q, functions, Value as V
from django.http import HttpResponseRedirect, JsonResponse
from .forms import *
from django.shortcuts import get_object_or_404, render, redirect
from erp_core.pagination import paginate
import pprint
from .filters import ProductFilter
from django.forms import inlineformset_factory
from django.db import transaction
from product.models import *
# Create your views here.


@login_required
def add_products(request):
    form = ProductsForm(request.POST or None)

    if request.method == "POST":
        # print(form.errors)
        # print(form2.errors)

        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            messages.add_message(request, messages.INFO, 'Program created sucessfully')
            return HttpResponseRedirect(reverse('product:detail', args=[product.id]))
    context = {
        "form": form,
        "type": "add",
    }
    return render(request, 'product/add_products.html', context)

# Details the Products


@login_required
def view_products(request):
    from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
    page_number = request.GET.get('page', 1)

    f = ProductFilter(request.GET, queryset=Program.objects.all().order_by("-created_at"))
    paginator = Paginator(f.qs, 20)

    # import pdb; pdb.set_trace()
    try:
        products = paginator.page(page_number)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    # products = Product.objects.all().order_by("-created_at")
    # products, pagination = paginate(request, queryset=f.qs, per_page=10, default=True)
    # upload_form = UploadFileForm()

    # products = Product.objects.all().order_by("-created_at")
    # products, pagination = paginate(request, queryset=products, per_page=10, default=True)
    # for page in pagination:
    #     print(page)
    context = {
        "products": products,
        # 'pagination': pagination,
        'filter': f,
        # 'upload_form': upload_form,

    }
    return render(request, 'product/view_products.html', context)


@login_required
def detail(request, pk):
    product = Program.objects.get(id=pk)
    context = {
        "product": product,
        "pk": pk
    }
    return render(request, "product/detail.html", context)


@login_required
def edit_product(request, product_pk):

    product = Program.objects.get(id=product_pk)
    form = ProductsForm(request.POST or None, instance=product)

    if request.method == "POST":
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('product:detail', args=[product.id]))
    context = {
        "form": form,
        "type": "edit",
    }
    return render(request, 'product/add_products.html', context)


@login_required
def code_settings(request):
    if CodeSetting.objects.exists():
        code_form = CodeSettingsForm(request.POST or None, instance=CodeSetting.objects.last())
    else:
        code_form = CodeSettingsForm(request.POST or None)

    if request.method == "POST":
        if code_form.is_valid():
            code_form.save()
            return HttpResponseRedirect(reverse('product:view_products'))

    context = {
        'code_form': code_form,
    }

    return render(request, "product/code_setting.html", context)


@login_required
def delete(request, pk):
    if request.method == 'POST':
        product = get_object_or_404(Product, pk=pk)
        product.delete()
        return HttpResponseRedirect(reverse('product:view_products'))


def dashboard(request):
    return render(request, "product/dashboard.html")


# @transaction.atomic
# @login_required
# # @permission_required('employee.add_employee', raise_exception=True)
# def import_data(request):
#     form = UploadFileForm(request.POST or None, request.FILES or None)
#     if request.method == "POST":
#         # form = UploadFileForm(request.POST, request.FILES)
#         # def user_func(row):
#         #     # print(row)
#         #     row[3] = make_password(row[3])
#         #     return row

#         # def prod_func(row):
#         #     # print(row)
#         #     user = User.objects.filter(username=row[0]).first()
#         #     row[0] = user
#         #     designation = Designation.objects.filter(name=row[1]).first()
#         #     row[1] = designation
#         #     return row

#         # def contact_func(row):
#         #     # print(row)
#         #     employee = Employee.objects.filter(code=row[0]).first()
#         #     row[0] = employee
#         #     return row

#         if form.is_valid():
#             file_data = request.FILES['file'].get_records()
#             # file_data = request.FILES['file']

#             # print(file_data)
#             # for row in file_data:
#             #     print(row['name'].first)
#             # import pdb
#             # pdb.set_trace()
#             # print(file_data)
#             # import pdb
#             # pdb.set_trace()
#             # for row in file_data:

#             #     if row['Levels Of Course'] is not None:
#             #         category = Category.objects.create(name=row['Levels Of Course'])

#             for row in file_data:
#                 # print(row)
#                 # user = User.objects.filter(username=row['username']).first()

#                 category = Category.objects.filter(name__icontains=row['Levels Of Course']).first()

#                 accademic_eligibility = Qualification.objects.filter(
#                     name__icontains=row['Accademic Eligibility']).first()

#                 area_of_interest = AreaOfInterest.objects.filter(
#                     name__icontains=row['Stream']).first()

#                 university = University.objects.filter(
#                     name__icontains=row['University']).first()
#                 product = Product.objects.create(
#                     name=row['Name'], code=row['Code'], price=row['Fee'], category=category, active=True)
#                 ielts = LanguageAssessmentTest.objects.filter(name="Ielts").first()
#                 gert = LanguageAssessmentTest.objects.filter(name="Gert").first()
#                 gort = LanguageAssessmentTest.objects.filter(name="Gort").first()
#                 # ContactForEmployee.objects.create(
#                 #     employee=employee, phone=row['phone'], alternate_phone=row['alternate_phone'])
#                 Attribute.objects.create(product=product, accademic_eligibility=accademic_eligibility, min_Percentage_requried=row['Minimum Percentage Required'], scholarship_options=row['Scholarship Options'], criteria_for_scholarship=row['Criteria For Scholarship'],
#                                          no_of_arrears_allowed=row['No Of Arrears Allowed'], other_interance_exams=row['Other Enterance Exams'],
#                                          stay_back_availability_in_months=row['Stay Back Availability in Months'], career_possibilities=row['Career Posibilities'], area_of_interest=area_of_interest, university=university)

#                 ProductLanguageAssesement.objects.bulk_create([
#                     ProductLanguageAssesement(product=product, language_assesement=ielts,
#                                               score=row['IELTS Score Required']),
#                     ProductLanguageAssesement(product=product, language_assesement=gert,
#                                               score=row['GERT Score Required']),
#                     ProductLanguageAssesement(product=product, language_assesement=gort,
#                                               score=row['GORT Score Required'])
#                 ])
#     return redirect("product:view_products")

product/templates/product/code_setting.html
{% extends "erp_admin/base.html" %}
{% load static %} 
{% block content %}

<div class="blank">
	 <div class="grid-form1">
	 	  <a href="{% url 'product:view_products' %}">Cancel</a>
  	       <h3 style="margin-top:20px;">Prefix</h3>
  	         <div class="tab-content">
						<div class="tab-pane active" id="horizontal-form">
							<form class="form-horizontal" id="code_setting" action="{% url 'product:code_settings' %}" method="post">{% csrf_token %}
							{{ code_form.non_field_errors }}
							{{ code_form.field_errors }}
							
								<div class="form-group">
									<label for="subject" class="col-sm-2 control-label">Prefix</label>
									<div class="col-sm-8 code-input">{{ code_form.prefix.errors }}
										{{ code_form.prefix }}
									</div>
								</div>

								<div class="form-group">
									<label for="subject" class="col-sm-2 control-label">Count</label>
									<div class="col-sm-8 code-input">{{ code_form.count_index.errors }}
										{{ code_form.count_index }}
									</div>
								</div>
								<div class="form-group">
									<label for="subject" class="col-sm-2 control-label">Number Of Characters</label>
									<div class="col-sm-8 code-input">{{ code_form.no_of_characters.errors }}
										{{ code_form.no_of_characters }}
									</div>
								</div>
								<div class="form-group">
									<label for="subject" class="col-sm-2 control-label">Program Code:</label>
									<div class="col-sm-8 code-input">
										<span id="code"></span>
									</div>
									
								</div>
								

								<div class="form-group">
									<div class="col-sm-8">
                						<button class="btn-primary btn">Submit</button>
                					</div>
                				</div>

								
							</form>
						</div>
					</div>
					
	</div>
</div>
{% endblock content %}
{% block jsscript %}
<script>
$(document).ready(function(){
	$("form#code_setting").on('input', function(e){
		var code = ""
		var prefix = $(this).find("#prefix").val()
		// console.log(prefix)
		if(prefix){
			code += prefix
			
			var no_of_characters = $(this).find("#no_of_characters").val()
			var count = $(this).find("#count_index").val() + ""
			
			function pad(num, size) {
			    var s = num+"";
			    while (s.length < size) s = "0" + s;
			    return s;
			}
			
			code += pad(count, no_of_characters)
			
			console.log(code)
		}
		$("#code").text(code)
	})
	$("form#code_setting").trigger('input')
})	
</script>



{% endblock jsscript %}

product/templates/product/dashboard.html
{% extends "erp_admin/base.html" %} {% load guardian_tags %} {% block content %}
{% load staticfiles %}
{% block head %}
<link href="{% static 'css/box_style.css' %}" rel='stylesheet' type='text/css' />

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
{% endblock head %}
<div class="blank">
    <div class="blank-page">
        <div class="row show-grid" style="margin-bottom:300px;">
            <div class="col-sm-12 col-md-12 col-xs-12">
                <h2>Programs</h2>
                <div class="row" style="margin-top:30px;">
                    {% if request.user.is_staff %}
                    <div class="col-sm-4 col-md-4 col-xs-12">
                        <div class="border_style bg2" align="center">
                            <a href="{% url 'product:add_products' %}">
                            <span style="color:#ffffff;">Add Program</span>
                            <div>
                            
                            </div>
                            </a>
                        </div>
                     
                    </div>
                    {% endif %}
                    <div class="col-sm-4 col-md-4 col-xs-12">
                        <div class="border_style bg1" align="center">
                            <a href="{% url 'product:view_products' %}">
                            <span style="color:#ffffff;">Program List</span>
                            <div>
                           
                            </div>
                            </a>
                        </div>
                     
                    </div>
                   
                   

                </div>
                
          </div>

        </div>
    </div>
</div>
        
   

{% endblock content %}

product/templates/product/detail.html
{% extends "erp_admin/base.html" %} 
{% load static tz %} 
{% get_current_timezone as TIME_ZONE %} 
{% block head %}
<style>
.row{
    margin-left:5px;
    margin-right:5px;
}
.tdCenter {
    text-align:right; /* center textbox horizontally */
    vertical-align: middle; /* center textbox vertically */

}
.text_size{
    font-size:18px!important;
    color:#000000!important;
}
mark {
    background-color:#f0ad4e;
    color:#ffffff;
}
.fabutton {
  background: none;
  padding: 0px;
  border: none;
}
</style>
{% endblock head %} 
{% block content %}

<div id="quotation-block" v-cloak>
    <div class="block">
        <a href="{{ request.META.HTTP_REFERER }}">Back </a>
        <div class="row show-grid">
            <div class="row">
                <div class="col-sm-8">
                    <h3>Program : {{ product.name }}</h3>
                </div>
                {% if request.user.is_staff %}
                            
                    <div class="col-sm-2" align="right">
                    <a href="{% url 'product:edit_product' product.pk %}"><i class="fa fa-edit"></i></a>
                    </div>
                    <div class="col-sm-2" align="right">
                        <form method="post" action="{% url 'product:delete' product.pk %}" onsubmit="remove(this, event)">
                            {% csrf_token %}
                            <button type="submit" class="fabutton">
                                <i class="fa fa-trash-o fa-fw"></i> 
                            </button>
                        </form>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>

    <div class="block">
        <div class="row show-grid">
            <div class="col-sm-12">
                <table class="table table-bordered">
                    <thead>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="2" style="text-align: center; font-size: 20px; color:black;">Program Details</td>
                        </tr>
                        {% if request.user.is_staff %}
                        <tr>
                            <th>Name</th>
                            <td>{{ product.name }}</td>
                        </tr>
                        <tr>
                            <th>Accademic Eligibility</th>
                            <td>{{ product.accademic_eligibility }}</td>
                        </tr>
                        <tr>
                            <th>Total Fee in INR</th>
                            <td><i class="fa fa-inr" aria-hidden="true"></i>{{ product.total_fee }}</td>
                        </tr>
                        
                        {% endif %}
                       
                    </tbody>
                </table>

            </div>
        </div>

    </div>
</div>
    




{% endblock content %} 

{% block jsscript %}

<script>
$(document).ready(function(){
    

    function remove(form, e){
        e.preventDefault()
        if(confirm('Confirm Delete')){
            form.submit()
        }
    }

});
</script>

{% endblock jsscript %}

product/templates/product/view_products.html
{% extends "erp_admin/base.html" %}
{% load static guardian_tags group_required %}
{% block head %}
<style type="text/css">
.fabutton {
  background: none;
  padding: 0px;
  border: none;
}
.table>thead>tr>th{
    color: #00ABE7!important;
    font-size: 15px!important;
    
}
@media print {

  a[href]:after {
    content: none!important;
  }
  .noprint{
    display:none!important;

  }
  }
</style>
{% endblock head %}
{% block content %}

<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Filters</h4>
      </div>
      <div class="modal-body">
        <form action="" method="get">
           
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">{{ filter.form.name.label }}</label>
                    {{ filter.form.name }}
                </div>
            </div>
            
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">Accademic Eligibility</label>
                    {{ filter.form.accademic_eligibility }}
                </div>
            </div>
            <div class="clearfix"></div>
            <button type="submit" class="btn btn-primary pull-right">Submit</button>
            <div class="clearfix"></div>
        </form>
      </div>
      <div class="modal-footer">
        
      </div>
    </div>
  </div>
</div>

<div class="blank">
    <div class="blank-page">
        <div class="row show-grid">
         <h2>
            Programs
            <a href="{% url 'product:add_products' %}" class="btn btn-link">
                <i class="fa fa-plus-square-o fa-2x"></i>
            </a>
         </h2>
            
        </div>
        <div class="row">
            <div class="pull-right">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#filter-modal">
                Apply Filters
                </button>
                <a href="{% url 'product:view_products' %}" class="btn btn-primary">Refresh</a>
                <a onclick="printDiv()" class="btn btn-primary btn-md pull-right" target="_blank"> <i class="fa fa-print fa-fw"></i> Print</a>
            </div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-12 table-responsive">
            <div id="print_data">

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            
                           {% if request.user.is_staff %}
                            
                                <th class="noprint">Edit</th> 
                                <th class="noprint">Delete</th>   
                            {% endif %} 
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in products %}
                        <tr>
                            <td>{{ forloop.counter0|add:products.start_index }}</td>
                            <td>
                                <a href="{% url 'product:detail' product.pk %}">
                                    {{product.name }}
                                </a>
                            </td>
                           
                            {% if request.user.is_staff %} 
                            
                            <td class="noprint">
                               <a href="{% url 'product:edit_product' product.pk %}"><i class="fa fa-edit"></i></a>
                            </td>
                            <td class="noprint">
                                <form method="post" action="{% url 'product:delete' product.pk %}" onsubmit="remove(this, event)">
                                    {% csrf_token %}
                                    <button type="submit" class="fabutton">
                                        <i class="fa fa-trash-o fa-fw"></i> 
                                    </button>
                                </form>
                            </td>
                            {% endif %}
                        </tr>

                        {% empty %}
                        <tr>
                            <td colspan="5">No Programs</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            <div id="pagination">
                <!-- {{ pagination|safe }} -->
                {% if products.has_other_pages %}
                      <ul class="pagination">
                        {% if products.has_previous %}
                          <li><a href="?page={{ products.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                          <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in products.paginator.page_range %}
                          {% if products.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                          {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                          {% endif %}
                        {% endfor %}
                        {% if products.has_next %}
                          <li><a href="?page={{ products.next_page_number }}">&raquo;</a></li>
                        {% else %}
                          <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                      </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>


{% endblock %}
{% block jsscript %}

<script>
$(document).ready(function(){
    

    function remove(form, e){
        e.preventDefault()
        if(confirm('Confirm Delete')){
            form.submit()
        }
    }

});
</script>
<script type="text/javascript">
    function printDiv() {    
    var printContents = document.getElementById('print_data').innerHTML;
    

    var originalContents = document.body.innerHTML;

     document.body.innerHTML = printContents;
    
     window.print();
     document.body.innerHTML = originalContents;
    }
    $("#pagination a").click(function(e){
        e.preventDefault()
        page_string = this.href.slice(this.href.indexOf("?") + 1)
        
        var query_string = ""   
        var search_query = window.location.search
        var query_obj = {}
        if(search_query){
            if(search_query.indexOf('?') > -1)
                search_query = search_query.substr(1)
            
            var searchQueryStrings = [search_query]
            if(search_query.indexOf('&') > -1)
                searchQueryStrings = search_query.split('&')
            
            searchQueryStrings.forEach(qs => {
                var query_array = qs.split('=')
                query_obj[query_array[0]] = query_array[1]
            })
        }
        
        query_obj['page'] = page_string.split('=')[1]
        for(var k in query_obj){
            query_string += k + '=' + query_obj[k] + '&'
        }
        
        // console.log(query_string, query_obj, window.location)
        window.location = window.location.pathname + "?" + query_string.slice(0, -1)
    })
</script>    


{% endblock jsscript %}